"""add enrichment status

Revision ID: b2683928a560
Revises: 7c0d77c1ea65
Create Date: 2026-07-22 18:36:27.649473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2683928a560'
down_revision: Union[str, Sequence[str], None] = '7c0d77c1ea65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column(
        "companies",
        sa.Column(
            "enrichment_status",
            sa.String(length=50),
            nullable=False,
            server_default='pending'
        )
    )

    op.execute(
        "UPDATE companies "
        "SET enrichment_status = 'pending' "
        "WHERE enrichment_status IS NULL"
    )

    op.alter_column(
        "companies",
        "enrichment_status",
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'enrichment_status')
    # ### end Alembic commands ###
