"""create authentication tables

Revision ID: cdc29aad74aa
Revises: 9f14c8a120de
Create Date: 2026-07-28 15:09:59.069509

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cdc29aad74aa"
down_revision: Union[str, Sequence[str], None] = "9f14c8a120de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.execute(
        sa.text(
            """
            INSERT INTO users (
                id,
                name,
                email,
                password_hash,
                is_admin,
                is_active,
                created_at,
                last_activity_at
            )
            VALUES (
                1,
                'Legacy Owner',
                'legacy-owner@autolead.invalid',
                '$2b$12$TheHrW0FHnMhErNjs.Grd.ApnYjo2UhB.vLTduLkliBuXpHFgnfbO',
                FALSE,
                FALSE,
                CURRENT_TIMESTAMP,
                NULL
            )
            """
        )
    )

    op.execute(
        sa.text(
            """
            SELECT setval(
                pg_get_serial_sequence('users', 'id'),
                1,
                TRUE
            )
            """
        )
    )
    op.create_foreign_key(
        None, "contact_submissions", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "credit_ledger", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "jobs", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "projects", "users", ["user_id"], ["id"])
    op.create_foreign_key(
        None, "spreadsheet_jobs", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "tool_requests", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "user_api_keys", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_api_keys", type_="foreignkey")
    op.drop_constraint(None, "tool_requests", type_="foreignkey")
    op.drop_constraint(None, "spreadsheet_jobs", type_="foreignkey")
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.drop_constraint(None, "jobs", type_="foreignkey")
    op.drop_constraint(None, "credit_ledger", type_="foreignkey")
    op.drop_constraint(None, "contact_submissions", type_="foreignkey")
    op.drop_table("users")
    # ### end Alembic commands ###
