/* eslint-disable react-hooks/set-state-in-effect */
import { Link } from "react-router-dom";
import { useCallback, useEffect, useState } from "react";
import api,{apiError} from "../api/client";
import LoadingScreen from "../components/LoadingScreen";
import Toast from "../components/Toast";
export default function Jobs(){const[jobs,setJobs]=useState([]),[page,setPage]=useState(1),[pages,setPages]=useState(0),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(""),[toast,setToast]=useState(null);
 const load=useCallback(async()=>{try{const{data}=await api.get(`/jobs/?page=${page}&limit=10`);setJobs(data.jobs);setPages(data.total_pages)}catch(e){setError(apiError(e,"Unable to load jobs."))}finally{setLoading(false)}},[page]);useEffect(()=>{load()},[load]);
 async function refresh(){try{setRefreshing(true);const{data}=await api.post("/jobs/refresh-pending?limit=20");await load();setToast({title:"Pending jobs checked",body:`${data.still_processing||0} processing · ${data.completed||0} completed · ${data.failed||0} failed · ${data.companies_saved||0} companies saved\nChecked ${data.checked||0} jobs`})}catch(e){setToast({type:"error",title:"Refresh failed",body:apiError(e)})}finally{setRefreshing(false)}}
 if(loading&&!jobs.length)return <main className="jobs-page"><LoadingScreen/></main>;
 return <main className="jobs-page"><div className="page-header"><div><div className="eyebrow">AUTOLEAD / JOBS</div><h1>Lead generation <span>jobs.</span></h1><p>Track your lead generation jobs and discovered businesses.</p></div><button className="crystal-button" onClick={refresh} disabled={refreshing}>{refreshing?"Checking Jobs...":"Refresh Pending Jobs"}</button></div>
 {error&&<p className="error-message">{error}</p>}<section className="jobs-list">{!jobs.length&&<div className="glass-card empty-state"><h2>No jobs yet</h2><p>Start your first lead generation job.</p><Link className="crystal-button" to="/tools/lead-generation">Create Lead Generation Job</Link></div>}
 {jobs.map(j=><Link key={j.id} to={`/jobs/${j.id}`} className="job-card glass-card"><div className="job-card-top"><div><div className="job-card-id">JOB #{j.id}</div><h2>{j.country}{j.province?` · ${j.province}`:""}</h2></div><span className={`job-status-badge ${j.status}`}>{j.status}</span></div>
 <div className="job-card-details"><div><span>Industries</span><strong>{j.industries.join(", ")}</strong></div><div><span>Target Leads</span><strong>{j.lead_count}</strong></div><div><span>Companies</span><strong>{j.company_count||0}</strong></div></div><div className="job-card-footer"><span>Firecrawl: <strong>{j.firecrawl_status}</strong></span><span>{new Date(j.created_at).toLocaleString()}</span><span className="view-job">View Details →</span></div></Link>)}</section>
 {pages>1&&<div className="pagination"><button className="pagination-button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>← Previous</button><span>Page {page} of {pages}</span><button className="pagination-button" disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Next →</button></div>}<Toast toast={toast} onClose={()=>setToast(null)}/></main>}
