import {useEffect,useRef,useState} from "react";import api,{apiError} from "../api/client";
export default function SpreadsheetEnrichment(){const[projects,setProjects]=useState([]),[projectId,setProjectId]=useState(""),[file,setFile]=useState(null),[googleUrl,setGoogleUrl]=useState(""),[job,setJob]=useState(null),[website,setWebsite]=useState(""),[columns,setColumns]=useState({linkedin:"",facebook:"",instagram:"",phone:"",email:""}),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");const key=useRef(null),guard=useRef(false);
useEffect(()=>{api.get("/projects/").then(r=>setProjects(r.data));},[]);
async function upload(e){e.preventDefault();if(guard.current||!file)return;guard.current=true;setBusy(true);key.current||=crypto.randomUUID();try{const body=new FormData();body.append("project_id",projectId);body.append("file",file);const r=await api.post("/spreadsheets/upload",body,{headers:{"Idempotency-Key":key.current}});setJob(r.data);key.current=null;}catch(x){setNotice(apiError(x));}finally{guard.current=false;setBusy(false)}}
async function importGoogle(){if(guard.current||!googleUrl)return;guard.current=true;setBusy(true);key.current||=crypto.randomUUID();try{const r=await api.post("/spreadsheets/google-sheet",{project_id:Number(projectId),url:googleUrl,idempotency_key:key.current});setJob(r.data);key.current=null;}catch(x){setNotice(apiError(x));}finally{guard.current=false;setBusy(false)}}
const headers=job?.sheets?.[0]?.headers||[];async function map(){try{setBusy(true);const r=await api.put(`/spreadsheets/${job.id}/mapping`,{website_column:website,field_columns:Object.fromEntries(Object.entries(columns).filter(([,v])=>v))});setJob(r.data);setNotice("Mapping saved.");}catch(x){setNotice(apiError(x));}finally{setBusy(false)}}
async function enrich(){try{setBusy(true);const r=await api.post(`/spreadsheets/${job.id}/enrich?limit=5`);setNotice(`${r.data.credits_added} cells filled; ${r.data.remaining} rows remain.`);const d=await api.get(`/spreadsheets/${job.id}`);setJob(d.data);}catch(x){setNotice(apiError(x));}finally{setBusy(false)}}
async function download(){const response=await api.get(`/spreadsheets/${job.id}/download.xlsx`,{responseType:"blob"});const url=URL.createObjectURL(response.data);const anchor=document.createElement("a");anchor.href=url;anchor.download=`spreadsheet-job-${job.id}.xlsx`;anchor.click();URL.revokeObjectURL(url);}
return <main className="dashboard-page"><button className="back-button" onClick={()=>location.assign("/tools")}>← Back to Tools</button><div className="eyebrow">AUTOLEAD / SPREADSHEET ENRICHMENT</div><h1>Fill missing business <span>data.</span></h1>
{!job?<form className="glass-card generation-card" onSubmit={upload}><div className="form-group"><label>Shared Project</label><select required value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="form-group"><label>CSV or Excel</label><input type="file" accept=".csv,.xlsx,.xlsm" onChange={e=>setFile(e.target.files[0])}/></div><button className="crystal-button" disabled={busy||!file}>{busy?"Uploading...":"Upload and Preview"}</button><div className="form-group"><label>Or public Google Sheets link</label><input type="url" value={googleUrl} onChange={e=>setGoogleUrl(e.target.value)}/></div><button type="button" className="secondary-button" disabled={busy||!projectId||!googleUrl} onClick={importGoogle}>Import Google Sheet</button></form>:
<section className="glass-card generation-card"><h2>{job.filename}</h2><p>{job.total_rows} rows · {job.sheets.length} sheet(s) · {job.credits_used} credits used</p>{job.status==="mapping"&&<><div className="form-group"><label>Website column</label><select value={website} onChange={e=>setWebsite(e.target.value)}><option value="">Select</option>{headers.map(h=><option key={h}>{h}</option>)}</select></div>{Object.keys(columns).map(f=><div className="form-group" key={f}><label>{f} output column</label><select value={columns[f]} onChange={e=>setColumns({...columns,[f]:e.target.value})}><option value="">Do not enrich</option>{headers.map(h=><option key={h}>{h}</option>)}</select></div>)}<button className="crystal-button" disabled={busy||!website} onClick={map}>Save Mapping</button></>}
{job.status!=="mapping"&&<div className="active-job-actions"><button className="crystal-button" disabled={busy} onClick={enrich}>{busy?"Processing...":"Enrich Next 5 Rows"}</button><button className="secondary-button" onClick={download}>Download Excel</button></div>}</section>}{notice&&<p>{notice}</p>}</main>}
